2.1.8 Exercises

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X >Y, and
 then see what kind of tensor you can get.

In [1]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])



In [2]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [3]:
result_less = X < Y
result_less


tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [4]:
result_greater = X > Y
result_greater


tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?


2.2.5 Exercises

1.Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository50 and
inspect their properties. What fraction of them has missing values? What fraction of
the variables is numerical, categorical, or text?


In [5]:
#pip install ucimlrepo
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [6]:
X.shape
X.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
dtype: int64

In [7]:
# Check for missing values
num_rows, num_columns = X.shape
missing_values_fraction = X.isnull().sum().sum() / (num_rows * num_columns)
missing_values_fraction



0.0

In [8]:
# Identify numerical, categorical, and text variables
numerical_columns = X.select_dtypes(include=['number']).shape[1]
categorical_columns = X.select_dtypes(include=['category', 'object']).shape[1]
text_columns = X.applymap(type).eq(str).sum().sum()  # Count text entries

print(f"Numerical columns: {numerical_columns}")
print(f"Categorical columns: {categorical_columns}")
print(f"Text columns: {text_columns}")

Numerical columns: 4
Categorical columns: 0
Text columns: 0


In [9]:
X

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

2.Try indexing and selecting data columns by name rather than by column number. The
pandas documentation on indexing has further details on how to do this.

In [10]:
#select single column by name
sepal_length = X["sepal length"]
print(sepal_length.head(1))


0    5.1
Name: sepal length, dtype: float64


In [11]:
#Select Multiple Columns by Name
selected_columns = X[["sepal length", "sepal width"]]
print(selected_columns.head(1))

   sepal length  sepal width
0           5.1          3.5


In [12]:
#Select a Range of Rows and Columns
subset = X.loc[0:4, ["sepal length", "sepal width"]]
print(subset)

   sepal length  sepal width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6


3.How large a dataset do you think you could load this way? What might be the limitations? Hint: consider the time to read the data, representation, processing, and memory
footprint. Try this out on your laptop. What happens if you try it out on a server?


4.How would you deal with data that has a very large number of categories? What if the
category labels are all unique? Should you include the latter?


==>To handle data with a large number of categories, you can group rare categories into an "Other" category or combine similar ones using domain knowledge. Use frequency or target encoding instead of one-hot encoding to save memory, or leverage embeddings for high-cardinality features. Dimensionality reduction techniques like PCA or clustering can also help reduce complexity, and sparse data structures are useful for memory efficiency. Avoid including features with all unique labels, such as user or transaction IDs, as they add no generalization value. Instead, derive meaningful features like counts or aggregates if needed. These approaches optimize both memory usage and model performance.

5.What alternatives to pandas can you think of? How about loading NumPy tensors from
a file ? Check out Pillow , the Python Imaging Library

In [13]:
from PIL import Image
import numpy as np

# Open the image using Pillow
img = Image.open("1.png")

# Convert the image to a NumPy array (tensor)
img_array = np.array(img)

# Display the shape of the resulting NumPy array
print(img_array.shape)



(600, 600, 4)


2.3.13 Exercises

Prove that the transpose of the transpose of a matrix is the matrix itself:

In [14]:
A=torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

In [16]:
tranpose_ofA=A.T
tranpose_ofA

tensor([[1, 3],
        [2, 4]])

In [17]:
tranpose_of_transpoe_ofA=tranpose_ofA.T

In [20]:
tranpose_of_transpoe_ofA==A
#proved

tensor([[True, True],
        [True, True]])

Given two matrices A and B, show that sum and transposition commute:
tranpose of A + transpose of B= tranpose of (A+B)

In [22]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
B = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)


LHS = A.T + B.T

RHS = (A + B).T

LHS==RHS
#proved

tensor([[True, True],
        [True, True],
        [True, True]])

Given any square matrix A, is A + A.T always symmetric? Can you prove the result by
using only the results of the previous two exercises?

In [24]:
#square MATRIX
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)


result = A + A.T

# Check if the result is symmetric: result == result^T
is_symmetric = torch.equal(result, result.T)

# Print the results
print("Matrix A:")
print(A)
print("\nA + A^T:")
print(result)
print("\nIs A + A^T symmetric?", is_symmetric)


Matrix A:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

A + A^T:
tensor([[ 2.,  6., 10.],
        [ 6., 10., 14.],
        [10., 14., 18.]])

Is A + A^T symmetric? True


We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?
Write your answer without implementing any code, then check your answer using code

In [26]:
import torch

X = torch.randn(2, 3, 4)


print("Shape of X:", X.shape)
print("len(X):", len(X))


Shape of X: torch.Size([2, 3, 4])
len(X): 2


For a tensor X of arbitrary shape, does len(X) always correspond to the length of a
certain axis of X? What is that axis?


==>Yes, for a tensor 𝑋 of arbitrary shape, the output of 
len(𝑋)
len(X) always corresponds to the length (or size) of the first axis (also known as the 0th dimension) of 𝑋

Run A / A.sum(axis=1) and see what happens. Can you analyze the results?

In [28]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float32)

# Compute row-wise sum
row_sums = A.sum(axis=1, keepdim=True)  # Keep dimensions for broadcasting

# Normalize rows of A
normalized_A = A / row_sums

print(A)

print(row_sums)

print(normalized_A)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 6.],
        [15.],
        [24.]])
tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000],
        [0.2917, 0.3333, 0.3750]])


When A/A.sum(axis=1) is computed:

Each row of A is normalized so that the sum of its elements equals 1.
Each element becomes a proportion of its row's total sum.
This is achieved through broadcasting, where the row sums are divided across all elements in the respective rows.

When traveling between two points in downtown Manhattan, what is the distance that
you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can
you travel diagonally?


No, you cannot travel diagonally in Manhattan since the streets and avenues form a grid. Travel is restricted to horizontal and vertical movements.

Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs
along axes 0, 1, and 2?


In [30]:
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)

# Summation along axes
sum_axis_0 = X.sum(axis=0)
sum_axis_1 = X.sum(axis=1)
sum_axis_2 = X.sum(axis=2)

# Print shapes
print("Shape of X:", X.shape)
print("Shape after summation along axis 0:", sum_axis_0.shape)
print("Shape after summation along axis 1:", sum_axis_1.shape)
print("Shape after summation along axis 2:", sum_axis_2.shape)

Shape of X: torch.Size([2, 3, 4])
Shape after summation along axis 0: torch.Size([3, 4])
Shape after summation along axis 1: torch.Size([2, 4])
Shape after summation along axis 2: torch.Size([2, 3])


Feed a tensor with three or more axes to the linalg.norm function and observe its
output. What does this function compute for tensors of arbitrary shape?

The torch.linalg.norm function computes the matrix or vector norm of a tensor, depending on its shape and the specified norm type

In [31]:
# Define a tensor with three axes (2, 3, 4)
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)

# Compute the Frobenius norm
norm = torch.linalg.norm(X)

print("Tensor X:", X)
print("Shape of X:", X.shape)
print("Frobenius norm of X:", norm)

Tensor X: tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
Shape of X: torch.Size([2, 3, 4])
Frobenius norm of X: tensor(65.7571)


It sums the squares of all elements in the tensor, then takes the square root.

For tensors of arbitrary shape:

The tensor is treated as a flattened 1D array, and the Frobenius norm is computed unless a specific axis or norm type is provided.

You want to compute the product ABC. Is
there any difference in memory footprint and speed, depending on whether you compute
(AB)C or A(BC). Why?


The product 
ABC can be computed either as 
(AB)C or 𝐴(𝐵𝐶)
However, the way the multiplication is performed can have an impact on memory footprint and speed due to the order of operations and the size of intermediate matrices involved.

Memory Footprint: The memory usage is smaller for 
(𝐴𝐵)𝐶 since the intermediate matrix is smaller.
Speed: 
(𝐴𝐵)𝐶 is faster because fewer operations are required.
In summary, computing 
(𝐴𝐵)𝐶 is more efficient both in terms of memory and computation speed due to the smaller intermediate matrix and fewer operations involved.

 Is there
any difference in speed depending on whether you compute AB or AC>? Why? What
changes if you initialize C = B> without cloning memory? Why?

AB is computationally cheaper because it involves fewer operations (800 operations) compared to 
𝐵𝐶 or 𝐴𝐶
When you multiply 
𝐴𝐵 it’s more efficient since the result has fewer elements, reducing the overall computational complexity.

Memory impact: If you transpose 
𝐵 to form 𝐶
you reuse memory without duplicating the data, saving memory but not affecting computational complexity.

Consider three matrices, say A, B, C ∈ R
100×200. Construct a tensor with three axes by
stacking [A, B, C]. What is the dimensionality? Slice out the second coordinate of the
third axis to recover B. Check that your answer is correct.

In [32]:

A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)


tensor = torch.stack([A, B, C])


recovered_B = tensor[1]


print(torch.allclose(recovered_B, B))

True


after stacking A , B and C the resulting tensor has shape of (3,100,200)
by accessing tensor[1] we can extract the coordinate of third axis which corresponds to B
torch.allclose(recovered_B, B) checks if the sliced tensor matches the original matrix B

The slice operation correctly recovers 
from the tensor, and the check will return True