2.1.8 Exercises

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X >Y, and
 then see what kind of tensor you can get.

In [2]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])



In [3]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [5]:
result_less = X < Y
result_less


tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
result_greater = X > Y
result_greater


tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?


2.2.5 Exercises

1.Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository50 and
inspect their properties. What fraction of them has missing values? What fraction of
the variables is numerical, categorical, or text?


In [3]:
#pip install ucimlrepo
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [13]:
X.shape
X.isnull().sum()

sepal length    0
sepal width     0
petal length    0
petal width     0
dtype: int64

In [14]:
# Check for missing values
num_rows, num_columns = X.shape
missing_values_fraction = X.isnull().sum().sum() / (num_rows * num_columns)
missing_values_fraction



0.0

In [18]:
# Identify numerical, categorical, and text variables
numerical_columns = X.select_dtypes(include=['number']).shape[1]
categorical_columns = X.select_dtypes(include=['category', 'object']).shape[1]
text_columns = X.applymap(type).eq(str).sum().sum()  # Count text entries

print(f"Numerical columns: {numerical_columns}")
print(f"Categorical columns: {categorical_columns}")
print(f"Text columns: {text_columns}")

Numerical columns: 4
Categorical columns: 0
Text columns: 0


In [23]:
X

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

2.Try indexing and selecting data columns by name rather than by column number. The
pandas documentation on indexing has further details on how to do this.

In [25]:
#select single column by name
sepal_length = X["sepal length"]
print(sepal_length.head(1))


0    5.1
Name: sepal length, dtype: float64


In [27]:
#Select Multiple Columns by Name
selected_columns = X[["sepal length", "sepal width"]]
print(selected_columns.head(1))

   sepal length  sepal width
0           5.1          3.5


In [30]:
#Select a Range of Rows and Columns
subset = X.loc[0:4, ["sepal length", "sepal width"]]
print(subset)

   sepal length  sepal width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6


3.How large a dataset do you think you could load this way? What might be the limitations? Hint: consider the time to read the data, representation, processing, and memory
footprint. Try this out on your laptop. What happens if you try it out on a server?


4.How would you deal with data that has a very large number of categories? What if the
category labels are all unique? Should you include the latter?


==>To handle data with a large number of categories, you can group rare categories into an "Other" category or combine similar ones using domain knowledge. Use frequency or target encoding instead of one-hot encoding to save memory, or leverage embeddings for high-cardinality features. Dimensionality reduction techniques like PCA or clustering can also help reduce complexity, and sparse data structures are useful for memory efficiency. Avoid including features with all unique labels, such as user or transaction IDs, as they add no generalization value. Instead, derive meaningful features like counts or aggregates if needed. These approaches optimize both memory usage and model performance.

5.What alternatives to pandas can you think of? How about loading NumPy tensors from
a file ? Check out Pillow , the Python Imaging Library

In [ ]:
from PIL import Image
import numpy as np

# Open the image using Pillow
img = Image.open("1.png")

# Convert the image to a NumPy array (tensor)
img_array = np.array(img)

# Display the shape of the resulting NumPy array
print(img_array.shape)



(600, 600, 4)
